#ifndef LIBCOMVERSION_H
#  error include libComVersion.h, not this header
#endif
#define EPICS_LIBCOM_MAJOR_VERSION 3
#define EPICS_LIBCOM_MINOR_VERSION 17
#define EPICS_LIBCOM_MAINTENANCE_VERSION 1
#define EPICS_LIBCOM_DEVELOPMENT_FLAG 1
